apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vote
  namespace: vote
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
