---

- name: Download minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: 0755
- name: Check minikube status
  shell: minikube status || true
  register: minikube_status_check
  changed_when: False

- name: Start minikube
  shell: >
    minikube start
    --vm-driver none
    --kubernetes-version v1.22.0
  when: "'apiserver: Running' not in minikube_status_check.stdout_lines"
